### ISSUE TITLE
Custom SASL Mechanisms

### ISSUE THREAD

**Issue by Bogdanp** [racket/sasl#3]
I've had to implement a non-standard mechanism today (see [this module](https://github.com/Bogdanp/racket-kafka/blob/9fd49634b454b0794fb1834b8225e32425740b6f/amazon-msk-sasl-lib/aws-msk-iam.rkt)) and I've had to depend on some internals to do so. 

I was going to make a PR that exposes the `sasl-ctx` struct and `set-sasl!`, but then realized probably the reason they're not already exposed is to avoid breaking encapsulation. If that's the reason, then maybe we could expose a `define-sasl-struct` form that expands to `(struct id sasl-ctx (field ...) struct-option ...)` and also defines a `transition-id!` procedure that guards that the first argument really is a custom ctx. If that's not the reason, then I'd also be happy with just exposing the struct and the setter. Either way, I'd be happy to do the work here, so let me know what you think.

EDIT: Perhaps a better alternative would be to make `sasl-{next,receive}-message` and `sasl-state` generic.

**Comment by Bogdanp** [comment]
Looks good to me. Would you like me to do a PR to add that functionality or are you planning to do it?

**Comment by rmculpepper** [comment]
I would welcome a PR. If you don't have time, then I can do it in a week or two.
